DESIGN_NAME: counter
VERILOG_FILES: "dir::src/counter.v"
CLOCK_PORT: clk
CLOCK_PERIOD: 24.0
PDK: gf180mcuD
STD_CELL_LIBRARY: gf180mcu_fd_sc_mcu7t5v0

FP_CORE_UTIL: 40
FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY_PCT: 55
GRT_ADJUSTMENT: 0.0
