DESIGN_NAME: picorv32
VERILOG_FILES:
  - "dir::../../src/picorv32.v"
CLOCK_PORT: clk
CLOCK_PERIOD: 25.0
PDK: sky130A
STD_CELL_LIBRARY: sky130_fd_sc_hd

FP_CORE_UTIL: 45
FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY_PCT: 55
GRT_ADJUSTMENT: 0.25
